### ISSUE TITLE
Add in Atlanta network channels ABC and NBC

### ISSUE THREAD

**Issue by purplescorpion1** [acidjesuz/EPG#10]
As daddylive uses sources from Atlanta can you add in ABC and NBC from Atlanta to your locals epg. You already have CBS and FOX there

Thanks

**Comment by acidjesuz** [comment]
Hey Bud,

I just took a look at my EPG and I don't see those two channels in my providers list. If the channel is not on the list you would have to provide me with exact name of those channels as their appear on your service (I don't know what IPTV provider you use) and I'll see if I can get those two channels rolling for you. I need exact name as you see that channel name in the list ex. ABC Atlanta or ABC Atl, I need to know the exact name.

aCiD

**Comment by purplescorpion1** [comment]
It is just ABC and NBC from Atlanta. 

To be more specific
ABC might show as ABC2 WSB-TV and will prob be channel number 2 or 32 (in Atlanta listings depending on service)

NBC might show as NBC11 WXIA-TV and will prob be channel number 10 or 11 (in Atlanta listings depending on service)

**Comment by acidjesuz** [comment]
Good morning,

I just added those two channels with few different variations to it, so if you get a chance please check and let me know if that worked, thanks.

aCiD

**Comment by purplescorpion1** [comment]
Yep those named ABC USA and NBC USA match to Atlanta 

Thanks
