### ISSUE TITLE
Request for US

### ISSUE THREAD

**Issue by crak3rjack** [acidjesuz/EPG#11]
Hi guide works super great appreciate the work, could you add this channel looked but did not found them there US & thanks!
1. NBC SPORTS NETWORK
2. MARQUEE SPORTS NETWORK
3. NICKTOONS US

**Comment by acidjesuz** [comment]
Hey there,

I just add Marquee and NickToons, doing a fresh pull as we speak so you can check it out in few minutes if it works for you or not. 

As for the NBC Sports Network channel, I believe that channel ceased operations on December 31, 2021, with its sports properties moved to USA Network, Peacock, and other NBCUniversal networks.

So I'm not really sure which NBC Sports your iptv provider is streaming.

aCiD

**Comment by crak3rjack** [comment]
Hi they do work could add them to the US GUIDE also, that's the one i'm using and thanks! :)

***NOTE***
In the "US GUIDE" that's how is spell "DISNEY JUNIOR 1" can you fix it to "DISNEY JR US"

**Comment by acidjesuz** [comment]
Doing a fresh pull, you can check in few minutes if Disney Jr US works for you if it does and you have no more issues, you can close this issue.

aCiD

**Comment by crak3rjack** [comment]
Appreciate it and one thing do you have a PayPal, so I can buy a coffee & thanks.

**Comment by acidjesuz** [comment]
Thank you, but no worries. I don't do this for any gains.
Just a little hobby in my spare time.

Next time you see someone in need help them out a bit.

aCiD
