### ISSUE TITLE
just adding: reccomend gzip 

### ISSUE THREAD

**Issue by Nsomnia** [acidjesuz/EPG#5]
45mb isnt huge comkpared to say epg_source1.xml.gz from epgsource1 but if your cron grabber job was set to gz it would probly make the size 10% with little/no import penalty even on tvs and single board computers. Just throwin gnit out there +1

**Comment by acidjesuz** [comment]
Hey Nsomnia,

I might just do that, I might provide two guides one with gz and one without it.

Right now I'm working on getting some Spanish speaking channels back to the guide (provider issues) when I get that resolved I'll get that gz going.

I might also do just English speaking channels guide, Spanish guide, combined guide and gz guide. 

So everyone could choose their flavor. Will see how that goes.

aCiD

**Comment by acidjesuz** [comment]
I just added .gz version of the guide, so there's two choice for people right now. Compressed and uncompressed. 

Thank you.
Have a great weekend.

Take Care,

aCiD
