### ISSUE TITLE
Channels missing

### ISSUE THREAD

**Issue by netstrem** [acidjesuz/EPG#7]
Hi, the Latam EPG is great but the US, locals and UK seem to be missing a lot of common channels (Lifetime, NBC, ABC, CBS, FX, BBC, Home and Health). Also there are a lot of channels coming in that are just numbers like 10.1, 13.2, 11.3 and I don't know what they are. Not bashing you, just curious about this.

**Comment by acidjesuz** [comment]
Hi there, it's not this EPG it's your providers playlist channels name. See, this guide is tailored towards once specific provider. So if your playlist has different channel names then it wont match those channels correctly or at all. I just check my guide and it's full and juicy with all the local, US, Latin American, UK and Canadian channels filled in with info.

**Comment by netstrem** [comment]
You are right, I searched for them and assigned them by number. Thank you very much for responding!
