### ISSUE TITLE
last epg date 6/28/2023

### ISSUE THREAD

**Issue by ulissesss** [acidjesuz/EPG#8]
Hi, looks like I can see the epg until the 28 of June , someone has same issue??
thanks!!

**Comment by LSDsl** [comment]
Problem with guide.xml file

**Comment by boeder9** [comment]
> Hi, looks like I can see the epg until the 28 of June , someone has same issue?? thanks!!

Acidjesuz is probably on a break/busy. I hope he updates the EPGs soon.
